## What is Broadcasting

`Broadcasting` in NumPy is a powerful feature that allows operations to be performed on arrays of different shapes. It does this by automatically expanding the smaller array along the larger array's dimensions:
- Starting with the trailing dimensions: The broadcasting operation starts by comparing the shapes of the two arrays from the end (trailing dimensions) towards the front.
- Compatibility Check: Two dimensions are compatible for broadcasting if:
    - they are equal, or
    - one of them is 1.
- Stretching the smaller dimension: If one of the arrays has a smaller dimension, NumPy will 'broadcast' the smaller array across the larger array so that they have compatible shapes. Broadcasting a dimension of size 1 means replicating the values along that dimension.
- No new data is created: It's important to note that broadcasting does not actually duplicate the smaller array; instead, it virtually replicates the array in memory during the operation.
- Performing the operation: Once the arrays have been virtually expanded to have compatible shapes, the element-wise operation is performed.

In [1]:
# example

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

B = np.array([1, 0, 1])

# B is broadcast to the shape of A and added to A
C = A + B

print(C)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
